### ISSUE TITLE
Add chat to pick screen

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#1897] opened 2018-02-01 01:13 UTC

**Comment by Flizz95** [comment] 2018-02-04 00:58
Noticed Carlos already fixed the chat issue today. I'm going to start on something else tomorrow.

**Comment by carlosrpg** [comment] 2018-02-05 23:48
Closed?

**Comment by Haganeko** [comment] 2018-02-06 00:06
Is it fixed? It was horribly broken a few days ago.

**Comment by Flizz95** [comment] 2018-02-06 00:09
Don't know didn't had the time today to look into Carlos code for the chat,
which apparently didn't work. Only know it for certain it breaks on
reconnecting.

**Comment by Flizz95** [comment] 2018-02-06 00:17
On the old code on sunday

**Comment by carlosrpg** [comment] 2018-02-06 00:17
steps to reproduce?

**Comment by Haganeko** [comment] 2018-02-06 00:23
Go into a game (might be limited to ardm)
Hotkeys will not work and kill messages stay forever
We suspect chat is eating the inputs due to it not closing after the game starts.

**Comment by Flizz95** [comment] 2018-02-06 00:23
Full game, reconnected with broken chat. Haven't been able to reproduce the
bug. Only happend in 2/4 game. But I noticed that more than just the chat
was broken in those games. In those games I also started without a picking
screen, out of the people who responded I seemed the only one to have
encountered that issue in those two games

**Comment by Flizz95** [comment] 2018-02-06 00:25
Those games did happen after a single ardm game

**Comment by carlosrpg** [comment] 2018-02-06 00:27
reconect must have the chat fix, otherwise is another problem, since the code I've done will not run at all

**Comment by carlosrpg** [comment] 2018-02-06 00:27
Had not tested ardm, I'll try that. Any reports on AP or CM?

**Comment by Haganeko** [comment] 2018-02-06 00:28
Not that I am aware.

**Comment by chrisinajar** [comment] 2018-03-12 22:14
Generally this works, we can open tickets for smaller bugs found with it

**Closed by chrisinajar** 2018-03-12 22:14 UTC
Labels: P2, Panorama
