### ISSUE TITLE
Turn the old Reflex Items into regular items

### ISSUE THREAD

**Issue by l34Um1** [OpenAngelArena/oaa#1607] opened 2017-12-15 12:42 UTC
With the removal of the Reflex core we will be moving the succesfull reflex items into the regular shop. Their effects remain the same as before but their numbers need to be adjusted. They no longer have simply HP, Armor and Magic Resistance but instead carry on the numbers from the items they now build out of.

Item builds out of | Old Reflex Item
--------------------|-------------------
Heart 2 | Regeneration Crystal
BKB 2 | Enrage Crystal
Lotus Orb 3 | Bubble Orb
Linkens 2 | Reflection Shard
Crimson Guard 2 | Reduction Orb
Lotus Orb 2 | Dispel Orb

**Comment by l34Um1** [comment] 2017-12-16 11:21
Ye and the corresponding core. So Linkens 2 + Upgrade Core 2 + Recipe = Reflection Shard

**Comment by imaGecko** [comment] 2017-12-16 12:10
Is anyone already doing it otherwise i'd just do it really quick

**Comment by Derk00** [comment] 2017-12-16 12:10
Well I am trying it atm, but its probably a lot quicker if you do it

**Comment by imaGecko** [comment] 2017-12-16 12:16
If you want to do it you can and I'll just review after

**Comment by Derk00** [comment] 2017-12-16 12:33
I will try

**Comment by l34Um1** [comment] 2017-12-16 13:33
Don't forget that items always go to level 5. So Heart 1 -> Core 1 -> Heart 2 -> Core 2 -> Regen Crystal 1 -> Core 3 -> Regen Crystal 2 -> Core 4 -> Regen Crystal 3

**Comment by Derk00** [comment] 2017-12-16 13:34
Yeah, what do I do with the numbers? Or do i just leave them as they are until Balance comes up with the correct numbers?

**Comment by l34Um1** [comment] 2017-12-16 13:35
Just reuse the numbers of the items it builds out of, we'll do proper numbers later.

**Comment by Derk00** [comment] 2017-12-16 13:35
Alright

**Comment by Derk00** [comment] 2017-12-16 13:44
Do they need to be able to be disassembled?

**Comment by warpdragon** [comment] 2017-12-16 14:13
This thread is a duplicate of #1590

**Comment by Derk00** [comment] 2017-12-16 14:14
How so? That post is purely about removing the reflex core from the game, and this is about turning items that required the reflex core into regular items

**Comment by Derk00** [comment] 2017-12-16 14:16
By the way Warp, do you know if what i did works? (I posted it in Documentation help)
First time im actually working with the files

**Comment by warpdragon** [comment] 2017-12-16 14:18
"Remove all Reflex Core requirements from existing item recipes"
it doesn't matter i'll close it.

**Comment by warpdragon** [comment] 2017-12-16 14:26
all you did was remove that component from the recipe, right? additionally, would you be so kind as to please add the "actual" name of the item under "ItemAliases" while you're in there (no spaces)? It's super hard to tell which reflex thing is which. having those names in there would help a lot. 

Oh and please keep the indentation style (block structure) so that "}" on line 23 needs to be moved over 4 spaces and the Value on line 22 needs to be moved to the right to line up with the values in lines 20 & 21.

I don't see anything else that stands out.

**Comment by Derk00** [comment] 2017-12-16 14:35
Thanks a lot, I'll give them proper names.

**Comment by Derk00** [comment] 2017-12-16 15:23
Baumi, don't you mean Lotus Orb 4? Or do I need to make a second level Bubble Orb?

**Comment by l34Um1** [comment] 2017-12-16 15:28
Yes, 2 levels of Bubble Orb

**Comment by Derk00** [comment] 2017-12-16 15:29
Should i give the Level 1 Bubble Orb have a 5 second duration instead of the full 10?

**Comment by warpdragon** [comment] 2017-12-16 15:31
"Just reuse the numbers of the items it builds out of, we'll do proper numbers later."

**Comment by Derk00** [comment] 2017-12-16 15:32
Okay

**Closed** 2017-12-30 00:31 UTC
Labels: great for new contributor, Items, KV, P1
