### ISSUE TITLE
Reflex invincibilty

### ISSUE THREAD

**Issue by eevee911** [OpenAngelArena/oaa#505] opened 2017-04-09 15:51 UTC
Reflex invincibilty not working

Amount x propably not defined
Reproducable yes

**Comment by spar36** [comment] 2017-04-09 15:53
Which item was this?

**Comment by eevee911** [comment] 2017-04-09 15:56
well i clicked it on the right time and didnt do anything

it's the sword you get for the reflex core with the 2400g recipe. cant look up the name

**Comment by Haganeko** [comment] 2017-04-09 19:12
Shard of Invincibility

**Comment by chrisinajar** [comment] 2017-04-10 04:09
duplicate of #494

**Closed by chrisinajar** 2017-04-10 04:09 UTC
