### ISSUE TITLE
Flying movement camping spot over dire spawn

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#322] opened 2017-03-25 05:47 UTC
![image](https://cloud.githubusercontent.com/assets/24883381/24319799/2ddc76c6-10ec-11e7-82bf-62269c249577.png)
The fountain can not hit someone at this position.

**Comment by Haganeko** [comment] 2017-04-10 17:44
Is this a duplicate of #428?

**Comment by KarmaticNeutral** [comment] 2017-04-10 20:37
No, they are on opposite sides of the spawn area but cover the same concept. The two could be combined to create one more complete ticket.

**Closed** 2017-05-18 02:57 UTC
Labels: bug, map
