### ISSUE TITLE
Cool, Possibly unique, thought for Caster Boots

### ISSUE THREAD

**Issue by doodly-hat** [OpenAngelArena/oaa#1958] opened 2018-02-07 00:46 UTC
Hey various devs for OAA:
I have a proposal. I'm sure that you've heard of caster boots before, but this is a little wonky so hear me out.

I feel like, even though you probably already know, I should state caster boots are an upgrade that boosts a caster's (such as Zeus) farming potential by making it easier to get money.

Passive GPM boots now reduce income from creeps by 50%, which I believe limits the farming potential of magic based farmers. These boots would add to the variety of viable builds, or at least make them more viable. For example, caster Shadow Fiend and Queen of Pain would become farming cores (pun intended).

The idea I have heard most often for caster boots is a straightforward spell amp increase vs. creeps. This idea definitely solves the problem, but it is uninspired. Those boots are basically a worse Kaya or Veil of Discord. 

Here is my first idea: Boots that add a counter every time a spell was cast, acting similar to the Greater Tranquil Boots, but the full charge lets you cast a fade bolt that deals 1/2 max hp, 1/3 max hp, etc. of non ancient units. Picture a Lina nuking a camp a few times, then finishing off the tougher creeps with the effect

Let me address the obvious flaw, Storm Spirit and spells with low cooldowns. Storm Spirits ultimate would have to not count towards the tally. I think that eventually, spells could have a "value" based off of the cooldown (Ether shock might have a value of 14/12/10/8 which is the cooldown of the spell at levels 1-4, whereas Shadow Poison might have a value of 2.5). The exact values are definitely subject to consideration. I like the idea of the value and the cooldown being related by a radical function [y= square root(x)] because it makes the boots better with spells that are spammable, most specifically Arc lighting, but worse with long cooldown abilities, which tend to be either not used for farming (many ultimates), or used for farming on right click heroes (Flame Guard). Specific examples would need to be addresses.

We could scale these boots by changing the damage, increasing the number of bounces, decreasing the cap/making each spell grant more value.

I really love Open Angel Arena, and I want to see this game grow to its full potential. I would love to work with you guys on this idea. You can contact me by discord @doodlyhat.

**Comment by doodly-hat** [comment] 2018-02-07 00:56
My second idea is similar to Arcane Echo, it makes creeps feel the effects of a spell twice. For example every time a Lina casts Dragon Slave, there is a chance that creeps hit by the spell take that damage again. If caster Sven were to stun the creeps, the stun duration is increased. 
This can scale by increasing the chase to proc, increasing the damage the second instance deals (30%-40%), or manipulating the cooldown on the boots, if one is implemented.
I don't like this idea as much because it isn't much more than an increase in spell amp.

**Comment by Chogex** [comment] 2018-02-07 02:09
Airwalkers
Boots + Null + Wraith + 400g
+6 / 7 / 9 / 13 / 20 Strength
+10 / 12 / 18 / 27 / 40 Agility
+10 / 12 / 18 / 27 / 40 Intelligence
+45 / 50 / 55 / 60 / 65 Movement Speed
Active: Force Dash
Pushes you 300 units in target direction.
Mana: 25
CD: 10 / 9 / 8 / 7 / 6
-- Farming passive for Level 2+
Passive: Magic Force
Increases your spell damage inflicted to neutral creeps by 30% / 40% / 50% / 60% / 70%.

This is something me & Arctangent came up with that I personally like a lot and feel like it fits in with the other boots.

**Comment by doodly-hat** [comment] 2018-02-07 04:20
I disagree that it fits in with the other boots. All of the other farming boots are unique. You can't buy a splash attack or a splinter (well, Drow can but...) in regular Dota. There isnt an item that gives you passive GPM. Tranquil boots kind of have a counter part, but Midas is very different in how it works. Those boots are really just a force staff and a veil that doesn't work on heroes. They're boring.

**Comment by doodly-hat** [comment] 2018-02-07 04:38
You guys always make sure that playing Open Angel Arena is unique enough to stand out from the other Angel Arena games, but similar enough so that it isn't inaccessible to new players. I think that just putting two or three items together is something I can find anywhere on the Dota 2 arcade. You guys aren't just any custom game. You make Dota 2 community better by furthering the game in a unique new way. I think that even if you don't use my idea, you guys can make something better than the Airwalkers.

**Comment by SquawkyArctangent** [comment] 2018-02-07 04:46
I feel like you're really overselling how different splash is from cleave, especially since it's not cleave literally because we didn't want to have to section the farming boots between melee and ranged. Not to mention, Phase splinter is basically just splash on top of that. And even on top of that, passive GPM is just a talent thing transferred to items ... if you completely forget that heroes have GPM automatically anyway.

Also, I wasn't aware Veil was a passive.

**Comment by Haganeko** [comment] 2018-02-07 10:23
I for one would argue we need to make treads more different from phase as well. But that's another topic.
As it is, Arcanes need a new farming function,because theirs is non interactive (Tranquils are also not that interactive but they're still in a better place). On the other hand, casters need farming boots. The conclusion seems obvious.

**Comment by SquawkyArctangent** [comment] 2018-02-07 10:25
Until you factor in that doing it that way entails either effectively deleting Guardian Greaves or putting in the work to create a non-boot version of 'em.

**Comment by imaGecko** [comment] 2018-02-07 10:28
Guardian Greaves are an interesting case because they are the only boots that you'd actually want to buy for their effect alone regardless of what farming effect they might have, the total cost of the boots very much show that as well.

**Comment by Haganeko** [comment] 2018-02-07 10:28
How so? Why would changing the way Arcanes work necessitate deleting Greaves?

**Comment by SquawkyArctangent** [comment] 2018-02-07 10:31
Because then they'd basically just be an Enigma and _maybe_ Viper item, as all the rest of the carriers are healers with really, really shit farming methods.

**Comment by imaGecko** [comment] 2018-02-07 10:33
Greaves = Arcanes
The initial item cost of buying greaves completely negates the option of going for them for the farming effect. They are directly tied to arcanes. 

Arcanes are merely a weaker version of greaves. Changing one changes the other.

**Comment by SquawkyArctangent** [comment] 2018-02-07 10:36
Yes, but changing Arcane's into a caster-based farming tool would entail making most of the heroes that would want Guardian Greaves instead have to stick to TPs or Tranqs, since making something that would both be a thing Zeus would want to accelerate his farming and be a thing that Witch Doctor would want to grab at all seems completely infeasible without making it outright overpowered for the former case.

**Comment by Haganeko** [comment] 2018-02-07 10:37
I have proposed just having Greaves as a non-farming boot in the past. I'd like to reiterate that. I think they work well as this investment a team can make for a fighting advantage.
And they're not an early game purchase, as Gecko has pointed out.

**Comment by SquawkyArctangent** [comment] 2018-02-07 10:39
If you have to make it so that a boot item can only be picked up on someone buying two boot items, then it's probably a sign that it either has no place in the game or it shouldn't be a boot item.

**Comment by l34Um1** [comment] 2018-02-07 10:43
I'm not sure what the problem with mana boots is? Greaves are stupid because they give you free purge but the GPM on them is fine, I see people picking up tranquils and TP boots frequently. What we really need is a boot for caster heroes that already have creep clearing abilities.

So like push boots or blink boots with no other farming components. Maybe a bit of creep spell amp but not much at all.

**Comment by Haganeko** [comment] 2018-02-07 10:49
The problem, as stated, is their farm is non interactive. It can't be denied, contested, fought over, or anything like that. Much as the name implies, it's passive.
One could argue the hero can actively work on it by upgrading them, but then we're removing one of the resources this hero needs and replacing it with the other.
Support boots should take effort.

**Comment by l34Um1** [comment] 2018-02-07 11:20
So contesting farm in terms of money is really more of an early game thing anyway. You are right they don't require effort though. What if we put some sort of timer on it that decays the passive gpm you get. So to get maximum GPM you have to periodically get a hero/boss/creep kill to reset that timer. Makes them take a bit of effort. And kinda gives some counterplay.

**Comment by Haganeko** [comment] 2018-02-07 11:48
We had a talk the other day about this. I suggested we add side objectives (capturable points were the most popular) around the map, and make some support boots reward completing those.

**Comment by l34Um1** [comment] 2018-02-07 12:04
Maybe bounty runes? We add like 4 spawn points, you have to pick one up to refresh the timer. This limits the amount of mana boots as well.

**Comment by Haganeko** [comment] 2018-02-07 13:07
The issue is that bounty runes do nothing except when the team has the boots.
We talked about capturable outposts, something that could give the team a buff, or points, a huntable wandering neutral...
ATan suggested outposts inside the base which could act as sanctuary against offside penalty once captured. They'd be the safe capture early, and transition into a stimulus to go after the enemy late (while not negating offside completely).

**Comment by l34Um1** [comment] 2018-02-07 13:16
Well bounties give gold and xp, that's not nothing.

**Comment by doodly-hat** [comment] 2018-02-07 16:12
With a game, the feeling of it is very important, and I think that spell amp vs creeps just wouldn't feel as satisfying as a magical fade bolt/ iron talon

**Comment by imaGecko** [comment] 2018-02-07 16:14
iron talon was never satisfying
a spell actually having impact is very much satisfying

**Comment by Chogex** [comment] 2018-02-07 16:39
The effect doesn't need to be complicated for the sake of being complicated.

**Comment by KarmaticNeutral** [comment] 2018-02-07 17:31
I don't like the idea of fading GPM that Buami proposed. It's unnecessarily complicated. If you want effort to be required, passive GPM is not a solution whatsoever, however I'm not against GPM.

Greaves are usually picked up on supports, so I suggest a support oriented farming mechanic for them. (whether that's GPM or something else I'm indifferent.)

We need a farming mechanic for spell based cores. I don't know what that would be, but I don't think this can be done on Greaves because supports need a support farming mechanism on those boots. (Not saying spell carries won't get greaves ever, but greaves are a support item)

I like the idea of a new kind of boot that has a spell amp effect against creeps to address this last point.

**Comment by Haganeko** [comment] 2018-02-07 17:39
I suggested a mechanic for the active support farm. But I guess that's up to another thread. This one was supposed to be about new caster boots. Oops.

**Comment by doodly-hat** [comment] 2018-02-07 17:59
I agree that caster boots should have an active component. That makes the boots reflect the user, which is (I think) a big part of the goal of farming boots.  I also agree that unessasary complication for the sake of complication isn't necessary. Maybe just scrap my idea. I think that it is closer to something I'd enjoy seeing in caster boots

**Closed** 2018-03-23 21:07 UTC
Labels: Discussion, Items
