### ISSUE TITLE
Fix Searing Arrow multishot proccing on Phase Boots splinter

### ISSUE THREAD

**Issue by Trildar** [OpenAngelArena/oaa#2009] opened 2018-02-20 10:57 UTC
I wonder if there's any chance of Valve fixing this, seeing as it probably affects Split Shot as well.

**Comment by Melongod** [comment] 2018-02-20 12:23
Can confirm it doesn't affect split shot.

**Comment by Trildar** [comment] 2018-02-20 12:33
How odd. Just how the flip did they even code this mess.

**Comment by imaGecko** [comment] 2018-02-20 12:40
well split shot is on attack landed, this is on attack started

**Comment by Trildar** [comment] 2018-02-20 13:41
Yeah. Probably only fires one extra because the Split Shot attacks at the same time. It's still technically broken because it eats mana for the Split Shot attacks as if it's using Searing Arrow, but don't seem to actually do the bonus damage. People might not even notice that happening though.

**Comment by imaGecko** [comment] 2018-02-20 13:47
https://youtu.be/qmcN0YnDmNo?t=1568
Baumi also made a video on that interaction in Legends of Dota

**Comment by Trildar** [comment] 2018-02-20 13:54
Splinter is completely different though, since it fully procs attack modifiers. What's happening with Greater Phase Boots is technically a Valve bug, but not one they're likely to fix soon, if ever.

**Comment by imaGecko** [comment] 2018-02-20 13:56
The cause could be the same, it doesn't matter what the searing arrows does when it hits, only that it launches more on attack, with splinters being attacks.

**Comment by Trildar** [comment] 2018-02-20 14:06
It's only supposed to do the multishot when Searing Arrows is used though. Which it wouldn't be if there wasn't some dumb bug with attack modifiers still performing their start of attack functions on attacks that aren't supposed to have attack modifiers.

**Comment by imaGecko** [comment] 2018-02-20 14:08
I'd guess the condition for multishot is 1.) searing arrows being active and 2.) making an attack
In the scope of regular dota there is no reason why it should consider any more than that

**Comment by Melongod** [comment] 2018-02-20 14:08
The Searing Arrows talent procs on attack land, and dusa split shot is on attack start. I think you have it backwards?

**Comment by imaGecko** [comment] 2018-02-20 14:09
searing arrow multishot procs on attack start

**Comment by Melongod** [comment] 2018-02-20 14:09
Then why does the infinite loop happen faster if oyu are standing next to the target?

**Comment by imaGecko** [comment] 2018-02-20 14:10
because splinters are on attack land

**Comment by Melongod** [comment] 2018-02-20 14:10
the distance the projectile has to travel is shorter, so it happens faster.

**Comment by imaGecko** [comment] 2018-02-20 14:10
because splinters are on attack land

**Comment by Melongod** [comment] 2018-02-20 14:10
Isnt that the issue though?

**Comment by Melongod** [comment] 2018-02-20 14:11
Is it possible to change the searing arrows talent to work the same way as dusa split shot?

**Comment by Melongod** [comment] 2018-02-20 14:11
Seeing as the loop doesn't occur on dusa.

**Comment by imaGecko** [comment] 2018-02-20 14:12
No splinters proccing on attack land is exactly what splinters are supposed to do.
Multishot proccing on any attack even those that don't even have attack modifiers is the problem

**Comment by Melongod** [comment] 2018-02-20 14:13
Does the same bug occur on drow?

**Comment by imaGecko** [comment] 2018-02-20 14:14
drow doesn't have multishot and phase boots don't apply attackmodifiers

**Comment by Melongod** [comment] 2018-02-20 14:14
With agh's she does.

**Comment by imaGecko** [comment] 2018-02-20 14:16
with aghs drow doesn't have multishot, she gains splinters on hit that proc attack modifiers

**Comment by Trildar** [comment] 2018-02-20 14:18
Drow Agh's splinters proc Greater Phase Boots splinters, but the reverse doesn't happen, so there's no infinite loop.

**Comment by Melongod** [comment] 2018-02-20 14:19
Ahh, i see.

**Comment by mikibun** [comment] 2018-06-09 14:43
Can this be closed or has this been fixed? @Trildar

**Comment by Trildar** [comment] 2018-06-09 15:47
No work has been done our end as far as I know. So it's still broken unless Valve happened to fix it.

**Closed** 2020-07-30 00:47 UTC
Labels: Bug, Items, lua
