### ISSUE TITLE
New bottles can not be used on allies

### ISSUE THREAD

**Issue by KarmaticNeutral** [OpenAngelArena/oaa#402] opened 2017-03-30 06:16 UTC

**Comment by Haganeko** [comment] 2017-03-30 06:23
This one I think is by design.

**Comment by Trildar** [comment] 2017-03-30 07:31
This might be fixable if it's deemed as important, but it was a known and accepted limitation of the current custom Bottles.

**Comment by Declow0** [comment] 2017-03-30 13:11
If bottle has attribute DOTA_ABILITY_BEHAVIOR_OPTIONAL_UNIT_TARGET and you try to use bottle on allies, game says target is not allowed (function OnSpellStart() doesn't run ). I can't find function for this action in API.

**Comment by Haganeko** [comment] 2017-03-30 13:15
That'd just make using the item more of a hassle (two buttons to press). And since they'll be dropping away, it probably won't be needed.

**Comment by warpdragon** [comment] 2017-03-30 13:33
The bottle needs to have the same targetting and fountain recharge mechanic (if the bottle has <3 charged, the fountain can recharge it to 3).

This "lack" of functionality feels, to players, like a mistake. If you're going to leave it without the additional bottle functionality I strongly suggest using a new icon to avoid this.

**Comment by Haganeko** [comment] 2017-03-30 14:47
I believe not recharging at the fountain is also design.

**Comment by warpdragon** [comment] 2017-03-30 14:50
u wot m8

**Comment by darklordabc** [comment] 2017-03-30 14:55
It's not by design it just has implemented in the remake yet, it would be easy to make bottle fill up to 3 charges when near fountain. Ctrl clicking is much harder to add.

**Comment by Declow0** [comment] 2017-03-30 15:07
@darklordabc Ok, need to check "modifier_fountain_aura". If unit has this set charges to 3 if unit has less. But where?

**Comment by Haganeko** [comment] 2017-03-30 15:42
Allowing recharge at fountain destroys the aspect of resource management, ie only having a finite amount of charges available at any point.
It is precisely because one can't recharge the bottle without picking another one up that it disappears - since one can't recharge it, there is no point to carrying an empty one around.

**Comment by warpdragon** [comment] 2017-03-30 15:46
yes that is very true. i forgot because the "bottle disappears" has not been implemented. Thanks @Haganeko . It's still a shame the bottle doesn't offer the traditional "heal your friend"

**Comment by Declow0** [comment] 2017-03-30 15:48
@warpdragon To "bottle disappears" just change "ItemPermanent" from "1" to "0"

**Comment by l34Um1** [comment] 2017-03-30 16:09
"Heal your friend" isn't traditional, it hasn't been in the game for long. I however want the bottle to function the same as it does in regular Dota, just with additional features and dissappearing when it goes empty. 
I don't think refill in the fountain messes with recource managment at all. It's going to be insignificant, bottle recource managment is going to matter outside of the well and if you want to go all the way back to fill a bottle up to an insignificant amount of charges then that's cool with me.

**Comment by warpdragon** [comment] 2017-03-30 16:10
so by "however i want the bottle function the same as it does in regular Dota" i take that to mean "heal your friend" = yes if possible?

**Comment by l34Um1** [comment] 2017-03-30 16:38
yes

**Comment by Haganeko** [comment] 2017-03-30 17:00
It is a weird thing, however - disappearing when empty only makes sense if the empty bottle is worth nothing, where if it can be refilled the empty version clearly has use.

**Comment by KarmaticNeutral** [comment] 2017-03-30 17:16
That's true, the effect of refilling bottles will become rare but it's better than someone expecting their 1 charge bottle to fill to 3 in fountain and thinking they found a bug when it doesn't work that way.

**Comment by Haganeko** [comment] 2017-03-30 18:00
And then when someone uses their last bottle charge on the way to the fountain, thinking to refill it?
Honestly, just change the icon a bit and call it "Angel's Bottle" or "Demon's Draught" or something.

**Comment by darklordabc** [comment] 2017-03-31 03:00
@Declow0 you could add a modifier to the item which has a thinker in lua, that has a 0.1 second think, and it checks if the owner has "modifier_fountain_aura_buff" and bottle has charges < 3 then set charges to 3.

**Comment by Haganeko** [comment] 2017-04-08 23:02
I think a conclusion was reached. Can we close this?

**Closed** 2017-04-08 23:07 UTC
Labels: discussion
