### ISSUE TITLE
Final Duel when teams are both near winning

### ISSUE THREAD

**Issue by Honeth** [OpenAngelArena/oaa#1290] opened 2017-07-17 15:20 UTC
At the moment if both teams are less then 5 kills away from winning and 1 of the teams triggers the final duel but they end up losing that duel they also lose the game with that same duel instead of it increasing the kill limit or triggering the final duel from the other team.

**Comment by Haganeko** [comment] 2017-08-04 19:24
This is a partial duplicate of #1059

**Closed by Haganeko** 2017-08-04 19:24 UTC
Labels: lua
